### ISSUE TITLE
I perform the following operations on the avenue dataset: py \ --work num=0 --consecutive=10 --dataset=avenue --cnl pool=32 \ --spatial f coreset=0.01 --temporal f coreset=0.01 --highlevel f coreset=0.but some errors were reported. May I ask what went wrong? Thank you very much for your answer!

### ISSUE THREAD

**Issue by WJL-prog** [SkiddieAhn/Paper-VideoPatchCore#2]
Traceback (most recent call last):--------------------------------------------------------------------| 0.00% [0/16 00:00<?]
  File "/root/Paper-VideoPatchCore-main/Memorization/run.py", line 52, in <module>
    main()
  File "/root/Paper-VideoPatchCore-main/Memorization/run.py", line 39, in main
    Featuring(cfg, device, train_folders, train_length, test_folders, test_length)
  File "/root/Paper-VideoPatchCore-main/Memorization/featuring.py", line 31, in __init__
    self.featuring_local(cfg, 'train', train_folders, train_length)
  File "/root/Paper-VideoPatchCore-main/Memorization/featuring.py", line 70, in featuring_local
    f_objects = clip[:,:,fidx,:,:].to(self.device) # (objects, 3, 64, 64)
IndexError: index 4 is out of bounds for dimension 2 with size 4

**Comment by SkiddieAhn** [comment]
I would like to ask if you entered the command correctly after performing object detection. Also, the path (working directory) should be set correctly as indicated in the GitHub README. I will provide the tutorial Colab code in the near future.

**Comment by WJL-prog** [comment]
hank you very much for your answer! However, I still have the previous problem. Is it my fault to set up the working directory or some other problem?
![屏幕截图 2024-12-12 132002](https://github.com/user-attachments/assets/ff356c0b-7b7b-4473-b908-4cbede9a090e)
![屏幕截图 2024-12-12 132053](https://github.com/user-attachments/assets/75cf7359-4bc0-419c-b109-7cb1b90eb107)

**Comment by WJL-prog** [comment]
Thank you very much for your answer! However, I still have the previous problem. Is it my fault to set up the working directory or some other problem?
![屏幕截图 2024-12-12 132002](https://github.com/user-attachments/assets/05c7c393-10f2-4b72-9099-f967604c796f)
![屏幕截图 2024-12-12 132053](https://github.com/user-attachments/assets/85ca8ca4-ac30-4ba2-819b-d1b8c66592b6)

**Comment by SkiddieAhn** [comment]
It seems that the issue arises from not performing **object detection**. Object detection should be conducted, and the detected objects must be stored in **'objects/{dataset}/{test or train}'**.

Please check the structure of our working directory through the following link:
https://github.com/SkiddieAhn/Paper-VideoPatchCore/blob/main/WORK_README.md

----------------------------------------------------------------------------------------------------------------------------

**Here is a collection of basic code for experimenting with the Avenue dataset. I will upload the tutorial code to GitHub in the near future. In the meantime, please refer to the information below.**

 1. For the dataset, you can download it using the link below:
 https://github.com/SkiddieAhn/Paper-VideoPatchCore/blob/main/DATA_README.md 


 2. Here is the command for Object Detection on the Avenue dataset: 
 ```
 python run.py --work_num=0 --dataset=avenue --consecutive=10 
```

 3. Here is the command for Memorization & Inference on the Avenue dataset: 
 ```
 python run.py --work_num=0 --consecutive=10 --dataset=avenue --cnl_pool=32 spatial_f_coreset=0.01 --temporal_f_coreset=0.01 --highlevel_f_coreset=0.01 
```

 4. If you’d prefer not to perform object detection and memorization directly, please refer to (Bounding box and Memory) on GitHub to use the files we used in our experiments!
 
 * GitHub (ReadMe): https://github.com/SkiddieAhn/Paper-VideoPatchCore?tab=readme-ov-file
 * Colab: https://colab.research.google.com/drive/1AuX7_f944_fcAA_4GPmutqqLMhOgBJUb?usp=sharing

----------------------------------------------------------------------------------------------------------------------------

**If this was helpful, please star our GitHub page (VideoPatchCore).**
Thank you for your attention to our work.
